<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find ur_description)/urdf/ur10.transmission.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur10.gazebo.xacro" />

  <property name="pi" value="3.14159265" />

  <!-- Inertia parameters -->
  <property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
  <property name="shoulder_mass" value="7.778" />
  <property name="upper_arm_mass" value="12.93" />
  <property name="forearm_mass" value="3.87" />
  <property name="wrist_1_mass" value="1.96" />
  <property name="wrist_2_mass" value="1.96" />
  <property name="wrist_3_mass" value="0.202" />

  <property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
  <property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
  <property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
  <property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
  <property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
  <property name="wrist_3_cog" value="0 -0.001156 -0.00149" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <property name="ur10_d1" value="0.1273" />
  <property name="ur10_a2" value="-0.612" />
  <property name="ur10_a3" value="-0.5723" />
  <property name="ur10_d4" value="0.163941" />
  <property name="ur10_d5" value="0.1157" />
  <property name="ur10_d6" value="0.0922" />
  
  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <property name="shoulder_offset" value="0.220941" />  <!-- measured from model -->
  <property name="elbow_offset" value="-0.1719" /> <!-- measured from model -->       
  
  <!-- link lengths used in model -->
  <property name="shoulder_height" value="${ur10_d1}" />
  <property name="upper_arm_length" value="${-ur10_a2}" />
  <property name="forearm_length" value="${-ur10_a3}" />
  <property name="wrist_1_length" value="${ur10_d4 - elbow_offset - shoulder_offset}" />
  <property name="wrist_2_length" value="${ur10_d5}" />
  <property name="wrist_3_length" value="${ur10_d6}" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
	<inertial>
		<mass value="${mass}" />
		<insert_block name="origin" />
		<inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
			iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
			izz="${0.5 * mass * radius * radius}" />
		</inertial>
  </xacro:macro>

  <xacro:macro name="ur10_robot" params="prefix">

  <link name="${prefix}base_link" >
    <visual>
      <geometry>
        <mesh filename="package://ur_description/meshes/ur10/visual/Base.dae" />
      </geometry>
	  <!-- <origin xyz="0.0 0.0 0.003" rpy="0.0 0.0 ${3.0 * pi / 4.0}" /> -->
	  <material name="LightGrey">
		  <color rgba="0.7 0.7 0.7 1.0"/>
	  </material>
    </visual>
    
 <!--   <collision>
      <origin rpy="0 0 0" xyz="0 0 0.025"/>
      <geometry>
        <cylinder length="0.04" radius="0.09"/>
      </geometry>
    </collision>
	-->
	<collision>
		<geometry>
			<mesh filename="package://ur_description/meshes/ur10/collision/base.stl"/>
		</geometry>
	</collision>
	<xacro:cylinder_inertial radius="0.075" length="0.038" mass="${base_mass}">
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
	</xacro:cylinder_inertial>
  </link>

  <joint name="${prefix}shoulder_pan_joint" type="revolute">
    <parent link="${prefix}base_link" />
    <child link = "${prefix}shoulder_link" />
	<origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
	<axis xyz="0 0 1" />
    <limit lower="${-pi/2.0}" upper="${3.0 * pi / 2.0}" effort="330.0" velocity="2.16"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>
  
  <link name="${prefix}shoulder_link">
    <visual>
      <geometry>
          <mesh filename="package://ur_description/meshes/ur10/visual/Shoulder.dae" />
      </geometry>
	  <material name="LightGrey">
		  <color rgba="0.7 0.7 0.7 1.0"/>
	  </material>
    </visual>

  <!--  <collision>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="0.17" radius="0.08"/>
		</geometry>
    </collision>
    
    <collision>
      <origin rpy="0 ${pi/2.0} ${pi/2}" xyz="0 0.1 0"/>
		  <geometry>
			  <cylinder length="0.28" radius="0.08"/>
		  </geometry>
    </collision>
	-->
	
	<collision>
		<geometry>
			<mesh filename="package://ur_description/meshes/ur10/collision/shoulder.stl"/>
		</geometry>
	</collision>
	<xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
	</xacro:cylinder_inertial>
  </link>

  <joint name="${prefix}shoulder_lift_joint" type="revolute">
    <parent link="${prefix}shoulder_link" />
    <child link = "${prefix}upper_arm_link" />
	<origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />    
	<axis xyz="0 1 0" />
    <limit lower="${-pi}" upper="${pi}" effort="330.0" velocity="2.16"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="${prefix}upper_arm_link">
    <visual>
      <geometry>
        <mesh filename="package://ur_description/meshes/ur10/visual/UpperArm.dae" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
	  <material name="LightGrey">
		  <color rgba="0.7 0.7 0.7 1.0"/>
	  </material>
    </visual>

<!--	<collision>
		<origin rpy="0 0 0" xyz="0 0 0.30"/>
		<geometry>
			<cylinder length="0.7" radius="0.05"/>
		</geometry>
		<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
	</collision>
	-->
	<collision>
		<geometry>
			<mesh filename="package://ur_description/meshes/ur10/collision/upper_arm.stl"/>
		</geometry>
	</collision>
	
	<xacro:cylinder_inertial radius="0.075" length="${-ur10_a2}" mass="${upper_arm_mass}">
		<origin xyz="0.0 0.0 ${-ur10_a2/2.0}" rpy="0 0 0" />
	</xacro:cylinder_inertial>
  </link>

  <joint name="${prefix}elbow_joint" type="revolute">
    <parent link="${prefix}upper_arm_link" />
    <child link = "${prefix}forearm_link" />
	<origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 1.0 0.0" />
	<limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="${prefix}forearm_link">
    <visual>
       <geometry>
        <mesh filename="package://ur_description/meshes/ur10/visual/Forearm.dae" />
      </geometry>
	  <material name="LightGrey">
		  <color rgba="0.7 0.7 0.7 1.0"/>
	  </material>
    </visual>
    
<!--	<collision>
		<origin rpy="0 0 0" xyz="0 0 0.28"/>
 		<geometry>
			<cylinder length="0.635" radius="0.04"/>
		</geometry>
	</collision>
 
  <collision>
      <origin rpy="0 ${pi/2.0} ${pi/2}" xyz="0 0.07 0"/>
		  <geometry>
			  <cylinder length="0.24" radius="0.07"/>
		  </geometry>
    </collision>
	-->
	<collision>
		<geometry>
			<mesh filename="package://ur_description/meshes/ur10/collision/forearm.stl"/>
		</geometry>
	</collision>	
	<xacro:cylinder_inertial radius="0.075" length="${-ur10_a3}" mass="${forearm_mass}">
		<origin xyz="0.0 0.0 ${-ur10_a3/2.0}" rpy="0 0 0" />
	</xacro:cylinder_inertial>
  </link>

  <joint name="${prefix}wrist_1_joint" type="revolute">
     <parent link="${prefix}forearm_link" />
    <child link = "${prefix}wrist_1_link" />
    <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
    <axis xyz="0.0 1.0 0.0" />
    <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="${prefix}wrist_1_link">
    <visual>
      <geometry>
        <mesh filename="package://ur_description/meshes/ur10/visual/Wrist1.dae" />
      </geometry>
	  <material name="LightGrey">
		  <color rgba="0.7 0.7 0.7 1.0"/>
	  </material>
    </visual>

<!--    <collision>
    	<origin rpy="0 0 0" xyz="0.0 0.113 0.002"/>
      	<geometry>
        	<cylinder length="0.116" radius="0.045"/>
      	</geometry>
    </collision>
    <collision>
      <origin rpy="0 ${pi/2.0} ${pi/2}" xyz="0.0 0.06 0"/>
      <geometry>
      	<cylinder length="0.09" radius="0.045"/>
      </geometry>
    </collision>
	-->
	<collision>
		<geometry>
			<mesh filename="package://ur_description/meshes/ur10/collision/wrist_1.stl"/>
		</geometry>
	</collision>
	<xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
	</xacro:cylinder_inertial>
  </link>

  <joint name="${prefix}wrist_2_joint" type="revolute">
    <parent link="${prefix}wrist_1_link" />
    <child link = "${prefix}wrist_2_link" />
    <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
    <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
	<dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="${prefix}wrist_2_link">
    <visual>
      <geometry>
        <mesh filename="package://ur_description/meshes/ur10/visual/Wrist2.dae" />
      </geometry>
	  <material name="LightGrey">
		  <color rgba="0.7 0.7 0.7 1.0"/>
	  </material>
    </visual>

    <!--<collision>
      <origin rpy="${pi/2.0} 0 0" xyz="0.0 0 0.11"/>
      <geometry>
        <cylinder length="0.11" radius="0.045"/>
      </geometry>
	  </collision>-->
  <!-- 
    <collision>
      <origin rpy="0 ${pi/2.0} ${pi/2}" xyz="0 -0.05 0"/>
		  <geometry>
			  <cylinder length="0.22" radius="0.05"/>
		  </geometry>
    </collision>
-->
	<collision>
		<geometry>
			<mesh filename="package://ur_description/meshes/ur10/collision/wrist_2.stl"/>
		</geometry>
	</collision>
	<xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
	</xacro:cylinder_inertial>
  </link>

  <joint name="${prefix}wrist_3_joint" type="revolute">
    <parent link="${prefix}wrist_2_link" />
    <child link = "${prefix}wrist_3_link" />
    <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 1.0 0.0" />
    <limit lower="${-pi + (pi/4.0)}" upper="${pi + (pi/4.0)}" effort="54.0" velocity="3.2"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="${prefix}wrist_3_link">
    <visual>
      <geometry>
        <mesh filename="package://ur_description/meshes/ur10/visual/Wrist3.dae" />
      </geometry>
	  <material name="LightGrey">
		  <color rgba="0.7 0.7 0.7 1.0"/>
	  </material>
    </visual>

 <!--   <collision>
      <origin rpy="${pi/2.0} 0 0" xyz="0 0.068 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.045"/>
      </geometry>
    </collision>
	-->
	<collision>
		<geometry>
			<mesh filename="package://ur_description/meshes/ur10/collision/wrist_3.stl"/>
		</geometry>
	</collision>
	<xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_3_mass}">
		<origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
	</xacro:cylinder_inertial>
  </link>
  
  <joint name="${prefix}ee_fixed_joint" type="fixed">
    <parent link="${prefix}wrist_3_link" />
    <child link = "${prefix}ee_link" />
    <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
  </joint>

  <link name="${prefix}ee_link" />

  <xacro:ur10_arm_transmission prefix="${prefix}" />
  <xacro:ur10_arm_gazebo prefix="${prefix}" />

  </xacro:macro>
</robot>
